# AUTOGENERATED! DO NOT EDIT! File to edit: ../first_notebook.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../first_notebook.ipynb 3
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
